/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProposalsIndexRouteImport } from './routes/_app/proposals/index'
import { Route as AppProposalsProposalIdRouteImport } from './routes/_app/proposals/$proposalId'
import { Route as AppProposalsNewRouteImport } from './routes/_app/proposals/new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsIndexRoute = AppProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsProposalIdRoute = AppProposalsProposalIdRouteImport.update({
  id: '/proposals/$proposalId',
  path: '/proposals/$proposalId',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsNewRoute = AppProposalsNewRouteImport.update({
  id: '/proposals/new',
  path: '/proposals/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/proposals/$proposalId': typeof AppProposalsProposalIdRoute
  '/proposals/new': typeof AppProposalsNewRoute
  '/proposals/': typeof AppProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/proposals/$proposalId': typeof AppProposalsProposalIdRoute
  '/proposals/new': typeof AppProposalsNewRoute
  '/proposals': typeof AppProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/proposals/$proposalId': typeof AppProposalsProposalIdRoute
  '/_app/proposals/new': typeof AppProposalsNewRoute
  '/_app/proposals/': typeof AppProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/proposals/$proposalId' | '/proposals/new' | '/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/proposals/$proposalId' | '/proposals/new' | '/proposals'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/proposals/$proposalId'
    | '/_app/proposals/new'
    | '/_app/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposals/': {
      id: '/_app/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AppProposalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposals/$proposalId': {
      id: '/_app/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof AppProposalsProposalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposals/new': {
      id: '/_app/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AppProposalsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProposalsProposalIdRoute: typeof AppProposalsProposalIdRoute
  AppProposalsNewRoute: typeof AppProposalsNewRoute
  AppProposalsIndexRoute: typeof AppProposalsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProposalsProposalIdRoute: AppProposalsProposalIdRoute,
  AppProposalsNewRoute: AppProposalsNewRoute,
  AppProposalsIndexRoute: AppProposalsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
